apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: optank-webapp
  labels:
    app: optank-webapp
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: optank-webapp.blackdog0403.com
      http:
        paths:
          - path: /
            backend:
              serviceName: optank-webapp
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: optank-webapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: optank-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optank-webapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: optank-webapp
  template:
    metadata:
      labels:
        app: optank-webapp
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
      containers:
        - name: optank-webapp
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: log-volume
              mountPath:  /App/springbootsampleapp/logs
            - name: tmp-volume
              mountPath:  /tmp
          ports:
            - containerPort: 8080

