apiVersion: v1
kind: Service
metadata:
  name: optank-webapp-green
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: optank-webapp-green
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: optank-webapp-green
  labels:
    app: optank-webapp-green
 spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: optank-webapp-green
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optank-webapp-green
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: optank-webapp-green
  template:
    metadata:
      labels:
        app: optank-webapp-green
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
      containers:
        - name: optank-webapp-green
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: log-volume
              mountPath:  /App/springbootsampleapp/logs
            - name: tmp-volume
              mountPath:  /tmp
          ports:
            - containerPort: 8080

